# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
env:
  DB_STRING: ${{ secrets.DB_STRING }}

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: create env file
        run: |
          touch .env
          echo DB_STRING=${{ secrets.DB_STRING }} >> .env
          echo DB=${{ secrets.DB }} >> .env
      - name: Delete gitignore
        run: |
          rm .gitignore
      - name: Push .env to repo
        run: |
          git add .
          git commit -m "environment variables"
      - run: npm install
      - run: pm2 restart server
